### ISSUE TITLE
Failed to provision the instant database server

### ISSUE THREAD

**Issue by zomars** [snaplet/docs-old#60]
Just upgraded to latest CLI and I can't seem to create an instant db:

```
➜  cal.com git:(main) ✗ snaplet db create --git --latest
✖ Failed to provision the instant database server
Unhandled error: getaddrinfo ENOTFOUND _api.internal

We have been notified, but if you need help now please contact us:
- Discord
- GitHub Issues
```

**Comment by jgoux** [comment]
Hey @zomars, it should be fixed! Could you try again?

**Comment by peterp** [comment]
@jgoux Incidentally could we capture that exception and report a generic error in the api side?

**Comment by zomars** [comment]
Should I upgrade first? @jgoux 

EDIT: it still not working:

<img width="668" alt="Captura de Pantalla 2022-07-18 a la(s) 10 30 28" src="https://user-images.githubusercontent.com/3504472/179558945-7cec0f83-9537-45d8-8783-f741ebbf81fb.png">

**Comment by peterp** [comment]
@zomars 🤔 an upgrade shouldn't be the problem, since this is on our api side

@jgoux I am able to run the command on our end; any ideas:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/44849/179559164-8b72f3d5-511d-4f1d-9aac-557dde715583.png">

**Comment by zomars** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/3504472/179560022-98743b86-fe79-4e3c-a07f-e51627d8ef91.png">

And can't create either

**Comment by peterp** [comment]
@zomars We've found the issue and it should work now!

**Comment by zomars** [comment]
Can confirm it works now. Thank you both @peterp @jgoux 🙏🏽

**Comment by zomars** [comment]
It stopped working today:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/3504472/180883043-307ee561-53a1-4882-9656-444771e99829.png">

**Comment by zomars** [comment]
Also, clicking on "Github Issues" is a [dead link](https://github.com/snaplet/feedback/issues)

**Comment by peterp** [comment]
> It stopped working today:

@zomars Taking a look right now!

**Comment by peterp** [comment]
@zomars It should be fixed now, unfortunately we were using the fly machines incorrectly so I had to remove your old database instance. We're going to ship a command we're you'll be able to manually destroy the instance as well.

**Comment by peterp** [comment]
Hey @zomars, we were provisioning the fly databases incorrectly, could you try again?

**Comment by zomars** [comment]
Trying now... Also, its there a way to extract the full DB url from from the `snaplet db create --git --latest` command? Im thinking something like:

```bash
DB_URL=$(snaplet db create --git --latest)
```

EDIT: This works

```bash
DB_URL=$(snaplet db url --git)
```

**Comment by peterp** [comment]
Fixed on our end. Thanks!
